telegram_token: "5470672804:AAHKuOe2apKOHMMZ8fxcCE7z-_fDl-VGeDE"
template_path: "/etc/telegrambot/template.tmpl"
time_zone: "Europe/Moscow"
time_outdata: "02/01/2006 15:04:05"
split_msg_byte: 10000
send_only: true