groups:
- name: containers
  rules:
 
  - alert: Container is down
    expr: 
      absent(container_start_time_seconds{name="medok"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Medok container is down for more than 30 seconds"
      description: "Medok container is down"

  - alert: Container is down
    expr: 
      absent(container_start_time_seconds{name="medok-database"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Database container is down for more than 30 seconds"
      description: "Database container is down"
  
  - alert: Container is down
    expr:
      absent(container_start_time_seconds{name="medok-grafana"})
    for: 30s
    labels:
      severity: "Critical"
    annotations:
      summary: "Critical: Grafana container is down for more than 30 seconds"
      description: "Grafana container is down"
      name: "Grafana container is down"

  - alert: Container is down
    expr: 
      absent(container_start_time_seconds{name="medok-prometheus"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Prometheus container is down for more than 30 seconds"
      description: "Prometheus container is down"

  - alert: Container is down
    expr: 
      absent(container_start_time_seconds{name="medok-promtail"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Promtail container is down for more than 30 seconds"
      description: "Promtail container is down"
      name: "Promtail container is down"

  - alert: Container is down
    expr: 
      absent(container_start_time_seconds{name="medok-node-exporter"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Node Exporter container is down for more than 30 seconds"
      description: "Node Exporter container is down"

  - alert: Container is down
    expr: 
      absent(container_start_time_seconds{name="medok-cadvisor"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Cadvisor container is down for more than 30 seconds"
      description: "Cadvisor container is down"

  - alert: Container is down
    expr: 
      absent(container_start_time_seconds{name="medok-alertmanager"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Alertmanager container is down for more than 30 seconds"
      description: "Alertmanager container is down"

  - alert: Container is down
    expr: 
      absent(container_start_time_seconds{name="medok-alert-bot"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Alert Bot container is down for more than 30 seconds"
      description: "Alert Bot container is down"
