groups:
- name: containers
  rules:
 
  - alert: Medok container is down
    expr: 
      absent(container_start_time_seconds{name="medok"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Medok container is down for more than 30 seconds"
      description: "Medok container is down"

  - alert: Database container is down
    expr: 
      absent(container_start_time_seconds{name="medok_database"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Database container is down for more than 30 seconds"
      description: "Database container is down"
  
  - alert: Container is down
    expr:
      absent(container_start_time_seconds{name="medok_grafana"})
    for: 30s
    labels:
      severity: "Critical"
    annotations:
      summary: "Critical: Grafana container is down for more than 30 seconds"
      description: "Grafana container is down"
      name: "Grafana container is down"

  - alert: Prometheus container is down
    expr: 
      absent(container_start_time_seconds{name="medok_prometheus"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Prometheus container is down for more than 30 seconds"
      description: "Prometheus container is down"

  - alert: Container is down
    expr: 
      absent(container_start_time_seconds{name="medok_promtail"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Promtail container is down for more than 30 seconds"
      description: "Promtail container is down"
      name: "Promtail container is down"

  - alert: Node Exporter container is down
    expr: 
      absent(container_start_time_seconds{name="medok_node_exporter"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Node Exporter container is down for more than 30 seconds"
      description: "Node Exporter container is down"

  - alert: Cadvisor container is down
    expr: 
      absent(container_start_time_seconds{name="medok_cadvisor"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Cadvisor container is down for more than 30 seconds"
      description: "Cadvisor container is down"

  - alert: Alertmanager container is down
    expr: 
      absent(container_start_time_seconds{name="medok_alertmanager"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Alertmanager container is down for more than 30 seconds"
      description: "Alertmanager container is down"

  - alert: Alert Bot container is down
    expr: 
      absent(container_start_time_seconds{name="medok_alert_bot"})
    for: 30s
    labels:
      severity: Critical
    annotations:
      summary: "Critical: Alert Bot container is down for more than 30 seconds"
      description: "Alert Bot container is down"
