server:
  http_listen_port: 0
  grpc_listen_port: 0


positions:
  filename: /tmp/positions.yaml

client:
  url: https://181575:eyJrIjoiZTI2NTdiOGY0NGM1NjM2MjI1ODRiZDgyOTUzOGY0MDcwNWM5ZmI2ZiIsIm4iOiJBUElLRVkiLCJpZCI6NjE3NTk3fQ==@logs-prod-eu-west-0.grafana.net/api/prom/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log