global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:    
    - targets: ['node-exporter:9100']
 
  - job_name: 'cadvisor'
    # scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8081']


remote_write:
  - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
    basic_auth:
      username: 365210
      password: eyJrIjoiZjBkM2I3NmY1OTRmNTdhNzM4NjUwZTZjMmU4YWYxZDRmZmNkYTdkMSIsIm4iOiJQcm9tZXRoZXVzS2V5IiwiaWQiOjYxNzU5N30=